global:
  resolve_timeout: 2m

route:
  receiver: default-receiver
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 3h

receivers:
  - name: default-receiver
    webhook_configs:
      - url: http://demo-app:3000/alert
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'service']
