global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerting_rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093

  - job_name: demo-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - demo-app:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: demo-app

  - job_name: order-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - order-exporter:9100
